name: nihongo_mochi_flutter
description: A new Flutter project for Nihongo Mochi.
version: 1.0.0+1

environment:
  sdk: '^3.8.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_tts: ^4.2.5
  google_mlkit_digital_ink_recognition: ^0.12.1
  drift: ^2.20.0
  drift_flutter: ^0.2.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.1.0
  path: ^1.9.0
  json_annotation: ^4.9.0
  flutter_widget_from_html: ^0.15.0
  google_fonts: ^6.2.1
  provider: ^6.1.2
  xml: ^6.5.0
  shared_preferences: ^2.2.3
  just_audio: ^0.9.36
  http: ^1.2.1
  archive: ^3.6.1
  crypto: ^3.0.3
  url_launcher: ^6.3.0
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  drift_dev: ^2.20.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/files/
    - assets/files/kana/
    - assets/files/kanji/
    - assets/files/words/
    - assets/files/words/meanings/
    - assets/files/grammar/
    - assets/files/grammar/lessons/
    - assets/files/common/
    - assets/files/exercices/
    - assets/files/langs/ar_SA/
    - assets/files/langs/bn_BD/
    - assets/files/langs/de_DE/
    - assets/files/langs/en_GB/
    - assets/files/langs/en_US/
    - assets/files/langs/es_ES/
    - assets/files/langs/fr_FR/
    - assets/files/langs/in_ID/
    - assets/files/langs/it_IT/
    - assets/files/langs/ja_JP/
    - assets/files/langs/ko_KR/
    - assets/files/langs/mn_MN/
    - assets/files/langs/pt_BR/
    - assets/files/langs/ru_RU/
    - assets/files/langs/th_TH/
    - assets/files/langs/ua_UA/
    - assets/files/langs/vi_VN/
    - assets/files/langs/zh_CN/
    - assets/files/langs/en_GB/grammar/
    - assets/files/langs/fr_FR/grammar/
    - assets/files/langs/ko_KR/grammar/
    - assets/files/langs/zh_CN/grammar/
    - assets/files/meanings/
    - assets/files/sounds/
    - assets/drawable/
    - assets/values/
    - assets/values-ar-rSA/
    - assets/values-bn-rBD/
    - assets/values-de-rDE/
    - assets/values-en-rGB/
    - assets/values-es-rES/
    - assets/values-fr-rFR/
    - assets/values-in-rID/
    - assets/values-it-rIT/
    - assets/values-ja-rJP/
    - assets/values-ko-rKR/
    - assets/values-mn-rMN/
    - assets/values-pt-rBR/
    - assets/values-ru-rRU/
    - assets/values-th-rTH/
    - assets/values-ua-rUA/
    - assets/values-vi-rVN/
    - assets/values-zh-rCN/
    - assets/font/

  fonts:
    - family: KanjiStrokeOrders
      fonts:
        - asset: assets/font/KanjiStrokeOrders.ttf
