name: nihongo_mochi_flutter
description: Learn Japanese with NihongoMochi.
version: 0.9.8+1

environment:
  sdk: '^3.8.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  cupertino_icons: ^1.0.2
  flutter_tts: ^4.2.5
  google_mlkit_digital_ink_recognition: ^0.12.1
  drift: ^2.34.2
  drift_flutter: ^0.3.1
  sqlite3_flutter_libs: ^0.6.0+eol

  path_provider: ^2.1.0
  path: ^1.9.0
  json_annotation: ^4.9.0
  flutter_widget_from_html: ^0.15.0
  google_fonts: ^8.2.0
  provider: ^6.1.2
  xml: ^6.5.0
  shared_preferences: ^2.2.3
  just_audio: ^0.9.46
  http: ^1.2.1
  archive: ^3.6.1
  crypto: ^3.0.3
  url_launcher: ^6.3.0
  package_info_plus: ^10.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.34.4
  build_runner: ^2.4.11
  json_serializable: ^6.8.0


flutter:
  generate: true
  uses-material-design: true
  assets:
    - lib/l10n/
    - assets/files/

    - assets/files/kana/
    - assets/files/kanji/
    - assets/files/words/
    - assets/files/words/meanings/
    - assets/files/grammar/
    - assets/files/grammar/lessons/
    - assets/files/common/
    - assets/files/exercices/
    - assets/files/langs/ar_SA/
    - assets/files/langs/bn_BD/
    - assets/files/langs/de_DE/
    - assets/files/langs/en_GB/
    - assets/files/langs/en_US/
    - assets/files/langs/es_ES/
    - assets/files/langs/fr_FR/
    - assets/files/langs/in_ID/
    - assets/files/langs/it_IT/
    - assets/files/langs/ja_JP/
    - assets/files/langs/ko_KR/
    - assets/files/langs/mn_MN/
    - assets/files/langs/pt_BR/
    - assets/files/langs/ru_RU/
    - assets/files/langs/th_TH/
    - assets/files/langs/ua_UA/
    - assets/files/langs/vi_VN/
    - assets/files/langs/zh_CN/
    - assets/files/langs/ar_SA/grammar/
    - assets/files/langs/bn_BD/grammar/
    - assets/files/langs/de_DE/grammar/
    - assets/files/langs/en_GB/grammar/
    - assets/files/langs/en_US/grammar/
    - assets/files/langs/es_ES/grammar/
    - assets/files/langs/fr_FR/grammar/
    - assets/files/langs/in_ID/grammar/
    - assets/files/langs/it_IT/grammar/
    - assets/files/langs/ko_KR/grammar/

    - assets/files/langs/mn_MN/grammar/
    - assets/files/langs/pt_BR/grammar/
    - assets/files/langs/ru_RU/grammar/
    - assets/files/langs/th_TH/grammar/
    - assets/files/langs/ua_UA/grammar/
    - assets/files/langs/vi_VN/grammar/
    - assets/files/langs/zh_CN/grammar/
    - assets/files/meanings/
    - assets/files/sounds/
    - assets/drawable/
    - assets/font/

  fonts:
    - family: KanjiStrokeOrders
      fonts:
        - asset: assets/font/KanjiStrokeOrders.ttf
